os: linux
dist: bionic

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

branches:
  only:
    - main
    - 1.x

before_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == 'nightly' ]]; then
      #ignore php version check on nightly build
      composer install --ignore-platform-reqs
    else
      composer install
    fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require phpunit/phpunit:^7; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then PHPUNIT=vendor/bin/phpunit; else PHPUNIT=phpunit; fi
  - $PHPUNIT --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
